// The honour-board maths (tier thresholds, board membership, milestone and
// approaching-board computation, formatting) lives in @workspace/scorecard so
// the mobile app and the website share one implementation — this file used to
// be a drifted fork of artifacts/cricket-club/src/lib/honour-boards.ts.
export {
  BOARDS,
  DEFAULT_BOARDS,
  HONOUR_TIER_CONFIG,
  MILESTONE_BOARDS,
  CONFIGURABLE_MILESTONE_BOARDS,
  DEFAULT_MILESTONE_THRESHOLDS,
  aggregateCareer,
  statToAggregated,
  getAvailableSeasons,
  buildTiers,
  computeBoard,
  getMilestoneStatus,
  getSeasonCrossings,
  getSeasonPromotions,
  getPlayerSeasonCrossings,
  getRecentPromotions,
  getApproachingMilestones,
  mergeBoardsMeta,
  type BoardKey,
  type BoardMeta,
  type BoardMetaOverride,
  type TierDef,
  type TierConfig,
  type AggregatedPlayer,
  type BoardRow,
  type BoardTier,
  type MilestoneThresholds,
  type MilestoneStatus,
  type SeasonCrossing,
  type PlayerSeasonCrossings,
  type PromotionEntry,
  type ApproachingEntry,
} from "@workspace/scorecard";
