import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import captainAuthRouter from "./captain-auth";
import adminsRouter from "./admins";
import captainsRouter from "./captains";
import awardVotingRouter from "./award-voting";
import playersRouter from "./players";
import statsRouter from "./stats";
import gradesRouter from "./grades";
import premiershipsRouter from "./premierships";
import importsRouter from "./imports";
import capsRouter from "./caps";
import lifeMembersRouter from "./life-members";
import honourBoardsRouter from "./honour-boards";
import awardsRouter from "./awards";
import socialCardsRouter from "./social-cards";
import socialDraftsRouter from "./social-drafts";
import storageRouter from "./storage";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(captainAuthRouter);
router.use(adminsRouter);
router.use(captainsRouter);
router.use(awardVotingRouter);
router.use(playersRouter);
router.use(statsRouter);
router.use(gradesRouter);
router.use(premiershipsRouter);
router.use(importsRouter);
router.use(capsRouter);
router.use(lifeMembersRouter);
router.use(honourBoardsRouter);
router.use(awardsRouter);
router.use(socialCardsRouter);
router.use(socialDraftsRouter);
router.use(storageRouter);

export default router;
