/**
 * Any Google Font for card kind templates (plan KTD12, U4). A template's text
 * styles may name any family in the committed catalogue
 * (`google-fonts-catalogue.json`, regenerated by
 * `scripts/src/build-google-fonts-catalogue.ts`). Renders load exactly the
 * families and weights a document uses, then explicitly load each face so
 * shrink-to-fit measures real metrics. A face that doesn't load is reported,
 * so the server marks the card "needs a look" instead of posting a fallback.
 *
 * The curated card fonts (`card-fonts.ts`) still load as before.
 */
import type { CardAdjustments } from "@/lib/pack-render";

export type CatalogueEntry = { family: string; category: string; weights: number[] };

/** Families the curated loader already provides; never requested again. */
const CURATED = new Set([
  "Anton",
  "Archivo Black",
  "Bebas Neue",
  "Cinzel",
  "EB Garamond",
  "Inter",
  "Kaushan Script",
  "Oswald",
  "Roboto Condensed",
  "Space Mono",
  "Teko",
]);

/** The default weight text renders at when a style doesn't set one. */
const DEFAULT_WEIGHT = 700;

/** The first family named in a CSS font-family value, unquoted; null for generic/var(). */
export function primaryFamily(fontFamily: string | undefined): string | null {
  if (!fontFamily) return null;
  const first = fontFamily
    .split(",")[0]
    ?.trim()
    .replace(/^['"]|['"]$/g, "")
    .trim();
  if (!first || first.startsWith("var(")) return null;
  if (/^(serif|sans-serif|monospace|cursive|fantasy|system-ui)$/i.test(first)) return null;
  return first;
}

/** Every (family, weight) a document's text styles use, by family. */
export function documentFontUsage(
  adj: CardAdjustments | null | undefined,
): Map<string, Set<number>> {
  const usage = new Map<string, Set<number>>();
  const add = (style: { fontFamily?: string; fontWeight?: number } | undefined) => {
    const family = primaryFamily(style?.fontFamily);
    if (!family) return;
    const weights = usage.get(family) ?? new Set<number>();
    weights.add(style?.fontWeight ?? DEFAULT_WEIGHT);
    usage.set(family, weights);
  };
  for (const layer of adj?.layers ?? []) {
    if (layer.hidden) continue;
    add(layer.style);
    for (const cell of layer.rows?.cells ?? []) add({ ...layer.style, ...cell.style });
    for (const overrides of Object.values(layer.rows?.variants ?? {})) {
      for (const style of Object.values(overrides)) add(style);
    }
  }
  return usage;
}

/** The available weight nearest to `wanted` (ties go to the heavier weight). */
export function nearestWeight(available: readonly number[], wanted: number): number {
  if (available.length === 0) return 400;
  return available.reduce((best, w) => {
    const d = Math.abs(w - wanted);
    const bd = Math.abs(best - wanted);
    return d < bd || (d === bd && w > best) ? w : best;
  });
}

/** The (family, weights) to request: catalogue families only, weights snapped to what exists. */
export function planFontRequests(
  usage: Map<string, Set<number>>,
  catalogue: readonly CatalogueEntry[],
): Array<{ family: string; weights: number[] }> {
  const byFamily = new Map(catalogue.map((e) => [e.family, e]));
  const out: Array<{ family: string; weights: number[] }> = [];
  for (const [family, wanted] of usage) {
    if (CURATED.has(family)) continue;
    const entry = byFamily.get(family);
    if (!entry) continue;
    const weights = [...new Set([...wanted].map((w) => nearestWeight(entry.weights, w)))].sort(
      (a, b) => a - b,
    );
    out.push({ family, weights });
  }
  return out;
}

/** The Google Fonts CSS API URL for the requests. */
export function googleFontsHref(requests: Array<{ family: string; weights: number[] }>): string {
  const params = requests
    .map(
      (r) =>
        `family=${encodeURIComponent(r.family).replace(/%20/g, "+")}:wght@${r.weights.join(";")}`,
    )
    .join("&");
  return `https://fonts.googleapis.com/css2?${params}&display=block`;
}

let cataloguePromise: Promise<CatalogueEntry[]> | null = null;

/** The catalogue, loaded on first use (kept out of the main bundle). */
export function loadFontCatalogue(): Promise<CatalogueEntry[]> {
  cataloguePromise ??= import("./google-fonts-catalogue.json").then(
    (m) => (m as { default: CatalogueEntry[] }).default,
  );
  return cataloguePromise;
}

function appendStylesheet(href: string): Promise<void> {
  return new Promise<void>((resolve) => {
    if (document.querySelector(`link[data-document-fonts][href="${href}"]`)) {
      resolve();
      return;
    }
    const link = document.createElement("link");
    link.rel = "stylesheet";
    link.href = href;
    link.setAttribute("data-document-fonts", "");
    link.onload = () => resolve();
    link.onerror = () => resolve();
    document.head.appendChild(link);
  });
}

/**
 * Load every catalogue font the document uses and return the families that
 * failed to load (empty when all loaded or none were needed). `document.fonts.load`
 * resolves with no faces — rather than rejecting — for a family that isn't
 * available, so an empty result counts as a failure.
 */
export async function ensureDocumentFonts(
  adj: CardAdjustments | null | undefined,
  catalogue?: readonly CatalogueEntry[],
): Promise<string[]> {
  if (typeof document === "undefined") return [];
  const usage = documentFontUsage(adj);
  if (usage.size === 0) return [];
  const requests = planFontRequests(usage, catalogue ?? (await loadFontCatalogue()));
  if (requests.length === 0) return [];
  await appendStylesheet(googleFontsHref(requests));
  const fonts = (document as Document & { fonts?: FontFaceSet }).fonts;
  if (!fonts?.load) return [];
  const failed = new Set<string>();
  for (const r of requests) {
    for (const w of r.weights) {
      try {
        const faces = await fonts.load(`${w} 32px "${r.family}"`);
        if (faces.length === 0) failed.add(r.family);
      } catch {
        failed.add(r.family);
      }
    }
  }
  return [...failed];
}
