import {
  ScrollText,
  Users,
  ClipboardList,
  Trophy,
  Award,
  Crown,
  GitCompare,
  Settings,
  Baby,
  CalendarDays,
  TrendingUp,
  Star,
  Home,
  Link as LinkIcon,
  FileText,
  ShoppingBag,
  Image,
  ListChecks,
  BarChart3,
  Shield,
  Flag,
  Mail,
  Phone,
  UserCog,
  Database,
  Upload,
  Medal,
  BookOpen,
  Megaphone,
  LayoutGrid,
  Ticket,
  type LucideIcon,
} from "lucide-react";

// Maps a stored nav icon key to a lucide icon component. Keep in sync with the
// ICON_KEYS list in artifacts/api-server/src/routes/nav-items.ts.
export const NAV_ICON_MAP: Record<string, LucideIcon> = {
  scrollText: ScrollText,
  users: Users,
  clipboardList: ClipboardList,
  trophy: Trophy,
  award: Award,
  crown: Crown,
  gitCompare: GitCompare,
  settings: Settings,
  baby: Baby,
  calendarDays: CalendarDays,
  trendingUp: TrendingUp,
  star: Star,
  home: Home,
  link: LinkIcon,
  fileText: FileText,
  shoppingBag: ShoppingBag,
  image: Image,
  listChecks: ListChecks,
  barChart3: BarChart3,
  shield: Shield,
  flag: Flag,
  mail: Mail,
  phone: Phone,
  userCog: UserCog,
  database: Database,
  upload: Upload,
  medal: Medal,
  bookOpen: BookOpen,
  megaphone: Megaphone,
  layoutGrid: LayoutGrid,
  ticket: Ticket,
};

export function navIcon(key: string | null | undefined): LucideIcon | null {
  if (!key) return null;
  return NAV_ICON_MAP[key] ?? null;
}
